trigger:
  - main

variables:
  NEXT_PUBLIC_API_BASE_URL: '$(apiBaseUrl)' # This will be set in Azure DevOps pipeline variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'
  env:
    NEXT_PUBLIC_API_BASE_URL: $(NEXT_PUBLIC_API_BASE_URL)

- script: |
    echo "Checking standalone directory structure:"
    ls -la $(System.DefaultWorkingDirectory)/.next/standalone/
    echo "Checking server.js specifically:"
    ls -la $(System.DefaultWorkingDirectory)/.next/standalone/server.js
  displayName: 'Verify build output structure'

- script: |
    cp -r $(System.DefaultWorkingDirectory)/public $(System.DefaultWorkingDirectory)/.next/standalone/
  displayName: 'Copy public assets'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.next/standalone'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- script: |
    cp $(System.DefaultWorkingDirectory)/.next/standalone/server.js $(Build.ArtifactStagingDirectory)/server.js
  displayName: 'Backup copy of server.js'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PredictionTimeAzure'
    appName: 'prediction-time-v1'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
    startUpCommand: 'NODE_ENV=production node server.js'