trigger:
  - main

variables:
  NEXT_PUBLIC_API_BASE_URL: '$(apiBaseUrl)' 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'
  env:
    NEXT_PUBLIC_API_BASE_URL: $(NEXT_PUBLIC_API_BASE_URL)

- script: |
    echo "Preparing deployment package..."
    mkdir -p $(Build.ArtifactStagingDirectory)/site
    # Copy standalone files first
    cp -r $(System.DefaultWorkingDirectory)/.next/standalone/* $(Build.ArtifactStagingDirectory)/site/
    
    # Create and populate .next directory with ALL necessary files
    mkdir -p $(Build.ArtifactStagingDirectory)/site/.next
    cp -r $(System.DefaultWorkingDirectory)/.next/static $(Build.ArtifactStagingDirectory)/site/.next/
    cp -r $(System.DefaultWorkingDirectory)/.next/types $(Build.ArtifactStagingDirectory)/site/.next/ || true
    cp $(System.DefaultWorkingDirectory)/.next/BUILD_ID $(Build.ArtifactStagingDirectory)/site/.next/
    cp $(System.DefaultWorkingDirectory)/.next/build-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/
    cp $(System.DefaultWorkingDirectory)/.next/prerender-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/
    cp $(System.DefaultWorkingDirectory)/.next/routes-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/
    cp $(System.DefaultWorkingDirectory)/.next/server/pages-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/ || true
    cp $(System.DefaultWorkingDirectory)/.next/required-server-files.json $(Build.ArtifactStagingDirectory)/site/.next/
    
    # Copy public directory if it exists
    if [ -d "$(System.DefaultWorkingDirectory)/public" ]; then
      cp -r $(System.DefaultWorkingDirectory)/public $(Build.ArtifactStagingDirectory)/site/
    fi
    
    echo "Deployment package contents:"
    ls -la $(Build.ArtifactStagingDirectory)/site/
    echo "Contents of .next directory:"
    ls -la $(Build.ArtifactStagingDirectory)/site/.next/
  displayName: 'Prepare deployment package'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PredictionTimeAzure'
    appName: 'prediction-time-v1'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
    startUpCommand: 'node server.js'