trigger:
  - main

variables:
  NEXT_PUBLIC_API_BASE_URL: '$(apiBaseUrl)' 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'
  env:
    NEXT_PUBLIC_API_BASE_URL: $(NEXT_PUBLIC_API_BASE_URL)

- script: |
    echo "Preparing deployment package..."
    mkdir -p $(Build.ArtifactStagingDirectory)/site
    
    # Debug current build output
    echo "Contents of build directory:"
    ls -la $(System.DefaultWorkingDirectory)/.next/standalone
    
    # Copy standalone files with verbose output
    cp -rv $(System.DefaultWorkingDirectory)/.next/standalone/* $(Build.ArtifactStagingDirectory)/site/
    
    # Make sure we preserve the nested .next directory structure from standalone
    cp -rv $(System.DefaultWorkingDirectory)/.next/standalone/.next $(Build.ArtifactStagingDirectory)/site/
    
    # Copy additional necessary files from the original .next
    cp -rv $(System.DefaultWorkingDirectory)/.next/static $(Build.ArtifactStagingDirectory)/site/.next/
    
    # Copy server directory if it exists
    if [ -d "$(System.DefaultWorkingDirectory)/.next/server" ]; then
      cp -rv $(System.DefaultWorkingDirectory)/.next/server $(Build.ArtifactStagingDirectory)/site/.next/
    fi
    
    # Copy manifest files
    cp $(System.DefaultWorkingDirectory)/.next/BUILD_ID $(Build.ArtifactStagingDirectory)/site/.next/ || true
    cp $(System.DefaultWorkingDirectory)/.next/build-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/
    cp $(System.DefaultWorkingDirectory)/.next/routes-manifest.json $(Build.ArtifactStagingDirectory)/site/.next/
    
    # Explicitly create and copy public directory
    echo "Copying public directory..."
    mkdir -p $(Build.ArtifactStagingDirectory)/site/public
    if [ -d "$(System.DefaultWorkingDirectory)/public" ]; then
      cp -rv $(System.DefaultWorkingDirectory)/public/* $(Build.ArtifactStagingDirectory)/site/public/
    else
      echo "WARNING: Public directory not found at $(System.DefaultWorkingDirectory)/public"
    fi
    
    echo "Final deployment package structure:"
    echo "Root directory:"
    ls -la $(Build.ArtifactStagingDirectory)/site/
    echo ".next directory:"
    ls -la $(Build.ArtifactStagingDirectory)/site/.next/
    if [ -d "$(Build.ArtifactStagingDirectory)/site/.next/server" ]; then
      echo ".next/server directory:"
      ls -la $(Build.ArtifactStagingDirectory)/site/.next/server/
    fi
    if [ -d "$(Build.ArtifactStagingDirectory)/site/public" ]; then
      echo "public directory:"
      ls -la $(Build.ArtifactStagingDirectory)/site/public/
    fi
  displayName: 'Prepare deployment package'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PredictionTimeAzure'
    appName: 'prediction-time-v1'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
    startUpCommand: 'node server.js'